name: Build Front.exe

on:
  workflow_dispatch:
  push:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: windows-latest
    
    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: '3.10' 
         
          environment-file: abc_conformations.yml 
          activate-environment: myenv 
          auto-activate-base: false

      - name: Install PyInstaller
        run: |
          conda install pyinstaller -c conda-forge

      - name: Build EXE
        run: |
          pyinstaller --onefile  Front.py

      - name: Upload EXE artifact
        uses: actions/upload-artifact@v4
        with:
          name: Front_Application
          path: dist/Front.exe
